### ISSUE TITLE
Support closing streams in ByteStreamProducer

### ISSUE THREAD

**Issue by ligustah** [go-openapi/runtime#46]
Hello,

I've been reworking an API to use go-swagger and stumbled across a few problems when implementing an endpoint that returns `image/jpeg`. One issue was that I retrieve images from a remote server via HTTP and want to send them to the client without having to buffer them in memory. The normal way of doing that would be simply copying the io.Reader and using something like `defer reader.Close()` to make sure that I don't leak resources.

However, with swagger (go-openapi) the actual response is only sent after my handler function is called, so the stream will be closed before a response can be returned to the client, leading to `panic: http: read on closed response body`.

To work around this I modified the `ByteStreamProducer` to check for `io.Closer` and automatically close the stream. I realize this might be considered a breaking change, because it might require people to wrap their payloads with `ioutil.NopCloser`. I can also see how this might not be a standard use case for swagger.

Either way, this is the code I added, in case you think this is useful:
```patch
diff --git a/vendor/github.com/go-openapi/runtime/bytestream.go b/vendor/github.com/go-openapi/runtime/bytestream.go
index dd8115f..73b2976 100644
--- a/vendor/github.com/go-openapi/runtime/bytestream.go
+++ b/vendor/github.com/go-openapi/runtime/bytestream.go
@@ -71,6 +71,9 @@ func ByteStreamProducer() Producer {
                }

                if rdr, ok := data.(io.Reader); ok {
+                       if closer, ok := data.(io.Closer); ok {
+                               defer closer.Close()
+                       }
                        _, err := io.Copy(writer, rdr)
                        return err
                }
```

**Comment by casualjim** [comment]
it's up to you to close the stream, the producer shouldn't do that imo
you can do a `defer strm.Close()` in your handler.

**Comment by ligustah** [comment]
If I use `defer strm.Close()` in my handler, the producer will not be able to read from it anymore, since it runs after my handler has returned.

**Comment by casualjim** [comment]
are you writing in  a goroutine?

**Comment by ligustah** [comment]
I'm not writing to the stream. It's an io.Reader.

Before using swagger the handler looked something like this:
```go
response, _ := http.Get("url")
defer response.Body.Close()
io.Copy(responseWriter, response.Body)
```

This worked, because my "producer" (io.Copy) was running in the same function call, but the swagger producers run after the defer statement is evaluated and as such cannot directly stream the response to the client.

**Comment by ligustah** [comment]
Without leaking the response.Body, that is.

**Comment by casualjim** [comment]
yeah sorry I was confused. Perhaps we add a ClosingByteStreamProducer instead so it doesn't break other code?

**Comment by ligustah** [comment]
Anything that works for you :+1:

**Comment by casualjim** [comment]
you can now create a bytestream producer or consumer with runtime.ByteStreamProducer(runtime.ClosesStream)

fixed by: 55d76b2319213cf30fdb7c4ae3a01541f5404c16

**Comment by waquidvp** [comment]
The fix in 55d76b2 doesn't actually solve the problem that has been mentioned in this issue. The fix seems to have added the closer to the `writer` but as the example code above shows, the close should happen on the `data`?
